modLoader="javafml"
loaderVersion="[33,)"
license="MIT"
[[mods]]
modId="mycelium_connect"
version="${version}"
displayName="Mycelium Connect"
#updateJSONURL=""
#displayURL=""
#logoFile=""
#credits=""
authors="2A5F"
description='''Mycelium Network'''
[[dependencies.mycelium_connect]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mycelium_connect]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2]"
    ordering="NONE"
    side="BOTH"
